### ISSUE TITLE
Can't jump to next bookmark in visual / visual block mode.

### ISSUE THREAD

**Issue by tecfu** [MattesGroeger/vim-bookmarks#101]
Is this expected behavior? If so, consider this issue a feature request. 
## Environment:

Ubuntu 14.04
vim 8.0

**Comment by MattesGroeger** [comment]
Hi @tecfu ,

it's my understanding that in visual mode one is not able to use custom shortcuts but only default movement keys. But please if anyone knows more than me, re-open this issue and point me in the right direction. Thx!
