### ISSUE TITLE
flashing, conflicts with Youcompleteme

### ISSUE THREAD

**Issue by zhenyangze** [MattesGroeger/vim-bookmarks#104]
I using both vim-bookmarks and Youcompleteme.　When type into and trigger Youcompleteme, the window will flash and falsh.

I try to remove plugins to find out the problem.

Then i remove the vim-bookmarks, and it change ok.

so, is there some conflicts with any existing keyboard shortcut or others between Youcompleteme and vim-bookmarks ?

**Comment by MattesGroeger** [comment]
Sorry it took me so long. Please re-open if still an issue.
