### ISSUE TITLE
[feature request] Make gutter letters for vim's/neovim's default marking system.

### ISSUE THREAD

**Issue by trusktr** [MattesGroeger/vim-bookmarks#107]
f.e., would be nice to press `ms` then see that marking in the gutter, and later press `s to go to it. The feature request would be specifically having that visual letter in the gutter.

**Comment by nkgm** [comment]
Using the default marks mechanism would, among other things, limit the amount of bookmarks per file, and you'd also have to deal with their persistence (viminfo/shada) and the potential mess that would ensue (not to mention you can't annotate vim marks). Don't get me wrong - marks are very useful, but they are a lower level mechanism, and the fact this plugin chooses to roll its own persistence is probably its greatest strength.

**Comment by MattesGroeger** [comment]
@nkgm Thanks for clarifying the aim of this plugin. I agree that the purpose of this plugin was/is to improve the default vim implementation by providing an independent solution.
