### ISSUE TITLE
Spaces in directories' names are not escaped (under Linux)

### ISSUE THREAD

**Issue by Hunter-Github** [MattesGroeger/vim-bookmarks#108]
1. To repro: make a directory with a space in its name, edit a file in it, add a bookmark, save, reload file, :BookmarkShowAll, press Enter to attempt to move to the line, watch the error.
2. Vim version: neovim 0.1.7
3. vim-bookmarks version: latest as of 1/30/2017. (using vim-plug for a package manager)

**Comment by MattesGroeger** [comment]
Sorry, I'm not using Linux. Can someone reproduce this issue still? Thx for reporting it @Hunter-Github
