### ISSUE TITLE
BookmarkShowAll brings up blank CtrlP

### ISSUE THREAD

**Issue by DominoTree** [MattesGroeger/vim-bookmarks#110]
CtrlP has one empty line for each bookmark I have set, but otherwise appears to have no data.  Both plugins are up to date, Vim 8.0.300

![screenshot](http://i.imgur.com/GHD0yUm.png)

**Comment by tracyone** [comment]
I can not reproduce in macOS and Ubunt 16.04.

What's your ctrlp setting?

here is mine:

```vim
" Set Ctrl-P to show match at top of list instead of at bottom, which is so
" stupid that it's not default
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_max_files = 50000

" Tell Ctrl-P to keep the current VIM working directory when starting a
" search, another really stupid non default
let g:ctrlp_working_path_mode = 'w'

let g:ctrlp_match_window = 'bottom,order:btt,min:1,max:20,results:20'
" Ctrl-P ignore target dirs so VIM doesn't have to! Yay!
let g:ctrlp_custom_ignore = {
            \ 'dir': '\v[\/]\.(git|svn|hg|build|sass-cache)$',
            \ 'file': '\v\.(exe|so|dll|o|d|proj|out)$',
            \ }
let g:ctrlp_extensions = ['tag', 'buffertag', 'dir', 'bookmarkdir']
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
```


My vim-bookmarks setting

```vim
let g:bookmark_auto_save = 1
let g:bookmark_no_default_key_mappings = 1
let g:bookmark_save_per_working_dir = 1
let g:bookmark_sign = '>>'
let g:bookmark_annotation_sign = '##'
let g:bookmark_auto_close = 1
```

**Comment by DominoTree** [comment]
I don't have any custom settings for `g:bookmarks` and only a custom command for `g:ctrlp`, but I tried again with the minimal `.vimrc` shown below and got the same behavior.

I also see the same thing on a fresh macOS install as well.


```
call plug#begin('~/.vim/plugged')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'MattesGroeger/vim-bookmarks'
call plug#end()
```

**Comment by DominoTree** [comment]
Same behavior

![screenshot](http://i.imgur.com/huxIHDl.png)

```
rs-ipfix git:(master) cat ~/.vim-bookmarks
let l:bm_file_version = 1
let l:bm_sessions = {'default': {'/Users/nprice/Projects/rs-ipfix/src/printer.rs': [{'sign_idx': 9500, 'line_nr': 1, 'content': 'extern crate nom;'},{'sign_idx': 9501, 'line_nr': 3, 'content': 'use std::collections::HashMap;'},],}}
let l:bm_current_session = 'default'
```

**Comment by tracyone** [comment]
I can not reproduce  with the minimal vimrc.

```vim
let $VIMFILES = $HOME.'/.vim'
let &rtp=&rtp.','.$VIMFILES
call plug#begin($VIMFILES.'/bundle')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'MattesGroeger/vim-bookmarks'
call plug#end()
filetype plugin indent on
syntax on
```

In following condition:

1. vim 8.0 1-300
2. zsh+tmux
3. bash
4. ubuntu 16.04 x64
5. gnome-terminal
6. text terminal
7. macoS

Can you apply this patch then try again


[patch.txt](https://github.com/MattesGroeger/vim-bookmarks/files/752429/patch.txt)

**Comment by DominoTree** [comment]
Now it looks like it's not seeing anything there.  I deleted my `.vim-bookmarks` file and tried again.

Thanks for your help with this, by the way.

![ss](http://i.imgur.com/HKjS375.png)

**Comment by DominoTree** [comment]
I went ahead and tried under bash (I usually use tmux and zsh) and nothing changed.  I also tried recompiling Vim with different options and it still had the same behavior.

If I manually add an annotation using `BookmarkAnnotate`, things appear to work properly.  I think that when they're being displayed, they're failing to read the `content` field when `annotation` does not exist.

```
let l:bm_file_version = 1
let l:bm_sessions = {'default': {'/Users/nprice/Projects/ipfix-json/src/main.rs': [{'sign_idx': 9500, 'line_nr': 1, 'content': 'extern crate elasticbuffer;'},{'sign_idx': 9501, 'line_nr': 3, 'content': 'extern crate ipfix;', 'annotation': 'test'},{'sign_idx': 9502, 'line_nr': 4, 'content': 'extern crate num_cpus;', 'annotation': 'test2'},],}}
let l:bm_current_session = 'default'
```

![ss](http://i.imgur.com/jEFevhf.png)

**Comment by MattesGroeger** [comment]
Sorry, I'm not really following this but does #113 maybe solve your issue with CtrlP?

**Comment by DominoTree** [comment]
I think there are two separate issues here, and #113 gets closer to solving one of them.

1: if you set `let g:bookmark_location_list = 1`, if you have CtrlP installed, `:BookMarkShowAll` will still open in CtrlP rather than in the QuickFix/Location list.

2: If you disable CtrlP entirely, the location list works, and it will show the `annotation` field if it exists, otherwise it will show the `contents` field.  When CtrlP is enabled, it will only show the `annotation` field, even if nothing is set, and will not fall back to the `contents field.  

I've added some screenshots below to help illustrate now that the QuickFix list works again.

![quickfix](http://i.imgur.com/4Tjh6LF.png)
![ctrlp](http://i.imgur.com/rPo9fkT.png)

**Comment by pass86** [comment]
I got the same problem.

**Comment by tracyone** [comment]
Yes,for now 

1. `g:bookmark_location_list` will be ignore if unite or ctrlp is installed.
2.  vim-bookmarks with ctrlp will only show the annotation field

I have tried your dotfile @DominoTree and I can not repoduce this problem.

**Comment by tracyone** [comment]
I have a question, two bookmarks of the first screen shot  in your last comment have no annotation field.

How did you do it?

**Comment by tracyone** [comment]
Ok I know what happen...you run BookmarkToggle..
