### ISSUE TITLE
Slow performance issue

### ISSUE THREAD

**Issue by trusktr** [MattesGroeger/vim-bookmarks#111]
I noticed that loading a session was taking a long time rather than being super quick like before. It's not a big deal while opening single files, but the time it takes to open many files in a session has become noticeable.

I don't think this was happening before.

Are there any options to make it faster? 

Specifically what happens is when I load a session I see vim render each file for a split second, whereas when I disable vim-bookmarks vim only displays a bunch of messages really fast at the bottom without rendering each window. Not sure if that helps point out the issue.

**Comment by nkgm** [comment]
@trusktr would you be able to test with `g:bookmark_auto_save = 0`?

**Comment by MattesGroeger** [comment]
Please re-open if still an issue 🙏
