### ISSUE TITLE
BookmarkShowAll fails without CtrlP installed

### ISSUE THREAD

**Issue by dustinmartin** [MattesGroeger/vim-bookmarks#112]
I get this error when executing `BookmarkShowAll`:

<img width="733" alt="screen shot 2017-02-08 at 9 30 55 am" src="https://cloud.githubusercontent.com/assets/141065/22743988/851cb064-ede1-11e6-8f91-0c0808b3486d.png">

I don't have CtrlP installed so I suspect that is the issue.

**Comment by tracyone** [comment]
You must install [ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim) and without lazyload ctrlp.vim
