### ISSUE TITLE
Jumping Vim

### ISSUE THREAD

**Issue by wysiecki** [MattesGroeger/vim-bookmarks#116]
Hi, very cool plugin, day saver, thank you very much, using it on daily basis. Just one question, can this jumping be fixed ?
 Its just ctrl-] on ubuntu.
It appears only when some bookmarks in the buffer are set.

MiniMovie attached

Thanks
Martin
[jumpingVim.mov.zip](https://github.com/MattesGroeger/vim-bookmarks/files/863084/jumpingVim.mov.zip)

**Comment by MattesGroeger** [comment]
@wysiecki sorry could you explain a bit more in detail what you mean with "jumping". Are the gutter icons appearing/disappearing?

**Comment by nkgm** [comment]
@wysiecki what keys are producing the effect shown in the movie file?

**Comment by MattesGroeger** [comment]
Thx @wysiecki for reporting this. I'm closing it for now as we are missing context.
