### ISSUE TITLE
Bookmark removed after selection from `BookmarksShowAll` with CtrlP integration

### ISSUE THREAD

**Issue by MattesGroeger** [MattesGroeger/vim-bookmarks#120]
Some bookmarks disappear once they get selected from the `ShowAll` window. I ran into this when adding bookmarks in multiple files and then navigating between them via `ShowAll`. Not sure what the exact steps to reproduce are, though.

**Comment by nkgm** [comment]
Can you provide some more context? Does this happen when using one of the integrations?

**Comment by MattesGroeger** [comment]
I just tested again and yes, I can only reproduce it with the CrtlP integration.

Steps to reproduce:
1. Open any file
2. Add bookmark `mm`
3. Show all bookmarks `ma`
4. Select bookmark

Cursor jumps at position but bookmark gets removed. Doing `ma` shows an empty list then.

**Comment by nkgm** [comment]
I was able to reproduce the problem with CtrlP (didn't get the chance to try the latest PR yet).  The steps to reproduce are:
1. Create a bookmark (annotated or not)
2. Without navigating away from the current split, run `BookmarkShowAll` (mapping or command) to show the CtrlP window. Navigate to the bookmark you just created. The bookmark is now gone.

If you were to move to another split (`BufLeave`) and then `BookmarkShowAll`, the bookmark will not be removed.

**Comment by nkgm** [comment]
You beat me by 8 seconds :)

**Comment by MattesGroeger** [comment]
@nkgm 😄 ... while testing I found another CtrlP-integration bug #123

**Comment by nkgm** [comment]
I confirm. Will have to check https://github.com/MattesGroeger/vim-bookmarks/pull/122

**Comment by MattesGroeger** [comment]
@nkgm ok, I'm testing and reviewing #122 just now as well 👍

**Comment by phaazon** [comment]
Same issue here, I reproduce everytime, and I have a warning showing up:

<img width="767" alt="screen shot 2017-07-12 at 17 14 46" src="https://user-images.githubusercontent.com/506592/28125027-ac8b4ecc-6725-11e7-9685-573d78b7cb48.png">

**Comment by mihaibirsan** [comment]
I can reproduce this 100% of the time with CtrlP. Scenario C below is indicative of a different bug, but might be relevant in tracking down this one as well.

I think the problem has to do with the fact that `BufLeave` is not called when replacing the buffer with itself in the same window. (Yet `BufEnter` is called nonetheless.)

1. Open any buffers F1 and F2, each containing previously saved marks
2. In buffer F1, set N new marks using `mm` and/or `mi`
3. Type `ma` to browse all bookmarks using CtrlP

#### Scenario A

A4. From the list, select a bookmark from F1
Expected: No bookmarks are lost. Cursor navigates to the selected bookmark line in F1.
Actual: The N new bookmarks are lost. Cursor navigates to the selected bookmark line in F1.

#### Scenario B

B4. From the list, select a bookmark from F2.
B5. Switch back to F1. (eg. using `<C-6>`)

Expected: No bookmarks are lost. Cursor navigates to the selected bookmark line in F2. All N bookmarks are still visible when switching back to F1.
Actual: *Works as expected.*

#### Scenario C

*In this scenario, let's assume each of the buffers is in its own tab, and `switchbuf=usetab,newtab`. You're editing F1 in the first tab.*

C4. From the list, select a bookmark from F2.

Expected: No bookmarks are lost. The second tab is activated and the cursor navigates to the selected bookmark line in F2.
Actual: No bookmarks are lost. The buffer in the first tab is replaced with F2 and the cursor navigates to the selected bookmark line in F2.

----

Plugin versions used:
https://github.com/ctrlpvim/ctrlp.vim/commit/7fa89fec125ce60a341f7c37dd769a8a31c49359
https://github.com/MattesGroeger/vim-bookmarks/commit/7b404c4739661ea1fc8ee0b24897376f0fbb320e

**Comment by radostyle** [comment]
I'm also affected by this.  I notice if create some bookmarks mm/mi then ma to show bookmarks, then I lose all my bookmarks. 

If I create some bookmarks mm/mi and then save the file.  The I reopen my file.  My bookmarks are there.  Then I ma to show all bookmarks.  Then I can go to each bookmark and they are not deleted.  Then I add some new ones with mm/mi,  then show them with ma.  Hit enter on one of them.  All my new bookmarks are deleted,  but the ones from before I had saved and exited are still there.

**Comment by radostyle** [comment]
It looks like switching buffers is enough to preserve the bookmarks.  Saving the buffer does not preserve the bookmarks, but switching to another buffer and coming back will keep the bookmarks.

**Comment by radostyle** [comment]
It is a hack but adding

 plugin/bookmark.vim | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/plugin/bookmark.vim b/plugin/bookmark.vim
index 133c148..4ccb57a 100644
--- a/plugin/bookmark.vim
+++ b/plugin/bookmark.vim
@@ -75,6 +75,7 @@ function! BookmarkToggle()
     call s:bookmark_add(file, current_line)
     echo "Bookmark added"
   endif
+  call s:auto_save()
 endfunction
 command! ToggleBookmark call CallDeprecatedCommand('BookmarkToggle', [])
 command! BookmarkToggle call BookmarkToggle()
@@ -118,6 +119,7 @@ function! BookmarkAnnotate(...)
     call s:bookmark_add(file, current_line, new_annotation)
     echo "Bookmark added with annotation: ". new_annotation
   endif
+  call s:auto_save()
 endfunction
 command! -nargs=* Annotate call CallDeprecatedCommand('BookmarkAnnotate', [<q-args>, 0])
 command! -nargs=* BookmarkAnnotate call BookmarkAnnotate(<q-args>, 0)

**Comment by tracyone** [comment]
@MattesGroeger I think this is a issue of vim-bookmarks' api, nothing to do with ctrlp.

**Comment by tracyone** [comment]
@radostyle What about this?

commit e1a8de2a7113e58aaced844c2925fe1ac7d5586d
Author: tracyone <tracyone@live.cn>
Date:   Sat Dec 16 12:28:46 2017 +0800

    fix #120: bookmars are cleared before save when using ctrlp.
    
    close #120

diff --git a/plugin/bookmark.vim b/plugin/bookmark.vim
index 133c148..de1d798 100644
--- a/plugin/bookmark.vim
+++ b/plugin/bookmark.vim
@@ -526,7 +526,7 @@ function! s:set_up_auto_save(file)
     augroup bm_auto_save
       autocmd!
       autocmd BufWinEnter * call s:add_missing_signs(expand('<afile>:p'))
-      autocmd BufLeave,VimLeave * call s:auto_save()
+      autocmd BufLeave,VimLeave,BufReadPre * call s:auto_save()
     augroup END
   endif
 endfunction
