### ISSUE TITLE
Add option to specify bookmark file name for bookmark_save_per_working_dir

### ISSUE THREAD

**Issue by shammellee** [MattesGroeger/vim-bookmarks#128]
I'd like to specify the file name vim-bookmarks looks for when the `bookmark_save_per_working_dir` option is enabled.

Something like…

```vim
let g:bookmark_save_per_working_dir_file = '.bookmarks'
```

**Comment by MattesGroeger** [comment]
Hi @shammellee , did you see this section of the [Readme.md](https://github.com/MattesGroeger/vim-bookmarks#bookmarks-per-working-directory)? This custom function allows to set your own file-name.

```
function! g:BMWorkDirFileLocation()
    return getcwd(). '/.bookmarks'
endfunction
```
