### ISSUE TITLE
Pressing escape whilst editing an existing annotated mark deletes the annotation

### ISSUE THREAD

**Issue by Roy-Orbison** [MattesGroeger/vim-bookmarks#129]
I understand that behaviour on a new mark, but when pressing `mi` to view the annotation, then `<Esc>` to cancel editing it, it gets converted to an unannotated mark.

**Comment by nkgm** [comment]
Normally you'd hit `Enter` to leave as is, but what happens when you've partially edited, then changed your mind. Guess the sensible thing would be to leave the previous value. What do you think @MattesGroeger?

**Comment by Roy-Orbison** [comment]
`<Esc>` Cancels everything else in Vim, I just don't expect it to effect a delete operation. Sounds better, @nkgm.

**Comment by rapilabs** [comment]
fyi `Ctrl-C` also cancels the edit

(I agree `Esc` should not remove the annotation)

**Comment by Roy-Orbison** [comment]
Don't know why, but when I first tried <kbd>Ctrl</kbd> + <kbd>C</kbd>, the annotation was still removed, then I closed & reopened Vim, tried again and it was retained. It had only been running for half a day after a server reboot.

**Comment by MattesGroeger** [comment]
Thanks for reporting and fixing it @Roy-Orbison 🙏
