### ISSUE TITLE
Bookmark List empty when started with -c flag

### ISSUE THREAD

**Issue by divramod** [MattesGroeger/vim-bookmarks#133]
Hey,

i try to automatically show me my bookmarks when opening a file.

I try it that way
```vim README.md -c "BookmarkShowAll"```
The bookmark window opens as expected but there are no bookmarks listed. I am sure that there is a .vim-bookmarks file in the folder because when i open vim in the following way 
```vim README.md```
and run ```:BookmarkShowAll``` manually as first command after vim opened, the bookmark window shows me my bookmarks.

Can somebody help me out here? I want to have my Bookmarks opened automatically.

**Comment by MattesGroeger** [comment]
Hi @divramod , thx for your question. Sorry you didn't get any help on this yet. I hope you could figure it out by now 🤞 .
