### ISSUE TITLE
Seeing this error message pretty regularly as part of auto save

### ISSUE THREAD

**Issue by arooni** [MattesGroeger/vim-bookmarks#136]
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[1]..bm#get_bookm
ark_by_sign:
line    1:
E716: Key not present in Dictionary: 9527
E15: Invalid expression: g:sign_map[a:file][a:sign_idx]
line    2:
E121: Undefined variable: line_nr
E116: Invalid arguments for function bm#get_bookmark_by_line(a:file, line_nr)
E15: Invalid expression: bm#get_bookmark_by_line(a:file, line_nr)
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[2]..bm#del_bookm
ark_at_line[1]..bm#get_bookmark_by_line:
line    1:
E716: Key not present in Dictionary: 0
E15: Invalid expression: g:line_map[a:file][a:line_nr]
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[2]..bm#del_bookm
ark_at_line:
line    2:
E716: Key not present in Dictionary: 0
line    3:
E716: Key not present in Dictionary: 0
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[1]..bm#get_bookm
ark_by_sign:
line    1:
E716: Key not present in Dictionary: 9514
E15: Invalid expression: g:sign_map[a:file][a:sign_idx]
line    2:
E121: Undefined variable: line_nr
E116: Invalid arguments for function bm#get_bookmark_by_line(a:file, line_nr)
E15: Invalid expression: bm#get_bookmark_by_line(a:file, line_nr)
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[2]..bm#del_bookm
ark_at_line[1]..bm#get_bookmark_by_line:
line    1:
E716: Key not present in Dictionary: 0
E15: Invalid expression: g:line_map[a:file][a:line_nr]
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[2]..bm#del_bookm
ark_at_line:
line    2:
E716: Key not present in Dictionary: 0
line    3:
E716: Key not present in Dictionary: 0
Error detected while processing function <SNR>96_auto_save[2]..BookmarkSave[1]..<SNR>96_refresh_line_numbers[12]..bm#update_bookmark_for_sign[1]..bm#get_bookm

**Comment by MattesGroeger** [comment]
I don't see these errors myself. Can you please provide more context as to which configurations and environment you are using?

**Comment by MattesGroeger** [comment]
This one looks like a similar error: #143
