### ISSUE TITLE
High light line is not removed after removing bookmark

### ISSUE THREAD

**Issue by johnzeng** [MattesGroeger/vim-bookmarks#142]
Hi , I can't remove the high light after removing a bookmark if I added some line before the bookmarked line. Any idea about it ? On my machine, this bug can be triggered by the following actions:

1. add a bookmark (let's say line 1 is marked)
2. add some new line above the bookmark( so the bookmarked line become line 2)
3. remove the bookmark (on line 2)

After removing the bookmark , line 2 is still high lighted....

I am using nvim

**Comment by MattesGroeger** [comment]
I can't reproduce this. How do you delete the Bookmark in step 3.?
