### ISSUE TITLE
BookmarkShowAll and CtrlP is not working

### ISSUE THREAD

**Issue by karamellpelle** [MattesGroeger/vim-bookmarks#144]
If I press `ma` The CtrlP window opens up a list of my bookmarks. However, entering one of these gives an error:

    Error detected while processing function <SNR>130_AcceptSelection[27]..ctrlp#bookmarks#accept:
    line   22:
    E37: No write since last change (add ! to override)

What is wrong? The `ma` command will fit good in my workflow...

And how do I show the annotation when my cursor is on the line of such a bookmark?

**Comment by tracyone** [comment]
hi,

This is not a issue of vim-bookmark. Vim protects you from
losing your work.

Please

```
:help E37
```

or add following code to your vimrc

```vim
set confirm
```

**Comment by karamellpelle** [comment]
But do I loose work (discarding the buffer) if I do a vim-bookmarks jump? It works well for the normal jump list (Ctrl-I, Ctrl-O); there I only get "No write since last change" if I try to quit vim without saving modified buffers. The same feature would be nice for _vim-bookmarks_ too.

Another question: Is it possible to show the annotation text when my cursor is on a line with a ☰ symbol?

Thank you!

**Comment by MattesGroeger** [comment]
Regarding your last question. This got recently merged in: https://github.com/MattesGroeger/vim-bookmarks/pull/148
