### ISSUE TITLE
[feature request] mark all bookmarks in the gutter with letters.

### ISSUE THREAD

**Issue by trusktr** [MattesGroeger/vim-bookmarks#145]
[vim-signature](https://github.com/kshenoy/vim-signature) has a feature where when you type something like `ms` to create a bookmark saved to `s`, then in the gutter it will show an `s` so it is easy to see where the `s` bookmark is.

Right now, it only puts something in the gutter for the generic bookmarks `mm`, but not other bookmarks. 

It would be super awesome if this plugin had that feature too. `vim-signature` has [a bug](https://github.com/kshenoy/vim-signature/issues/140) that `vim-bookmarks` doesn't, but `vim-signature` has the letter-marks feature. I'd like that feature of vim-signature, but without the annoying bug, so if you added this letter-mark feature to vim-bookmarks, that'd solve my problem. :D

**Comment by MattesGroeger** [comment]
Hi @trusktr ,

thx for suggesting this feature and making us aware of this nice `vim-signature` plugin.

Currently I don't think its feasible to refactor our plugin to have a similar functionality so I'm closing it for now. 

If anyone is eager to investigate the effort to implement such behaviour please feel free to re-open this and start a discussion.
