### ISSUE TITLE
Feature request: scroll bookmark to top instead of center

### ISSUE THREAD

**Issue by shammellee** [MattesGroeger/vim-bookmarks#150]
I'd like to scroll so that the bookmark is at the top of the screen when jumping to it.

**Comment by joelstrouts** [comment]
I think you could do this in your personal configuration by adding `z+` after each function call

**Comment by shammellee** [comment]
@joelstrouts thanks can you explain? Which functions are you talking about?

**Comment by joelstrouts** [comment]
looking into it a bit more, I was wrong in a few ways. First: this will work for jumping to the next/previous bookmarks, but not when selecting the bookmark from the quickfix list. Second, the correct mapping is `z<cr>` not `z+`.
<img width="741" alt="Screenshot 2019-07-11 at 07 35 37" src="https://user-images.githubusercontent.com/21037717/61027674-adfa2680-a3ae-11e9-9b8f-1620561f36f8.png">
To make the current line jump to the top of the screen when you jump to the next/previous bookmark you can remap the default commands like this:

```
nnoremap mn :BookmarkNext<cr>z<cr>
nnoremap mp :BookmarkPrev<cr>z<cr>
```

if you press `z<cr>` in normal mode it jumps the current line to the top of the screen. these mappings automatically call that function after you use the plugin's mapping

**Comment by shammellee** [comment]
@joelstrouts Thanks! `:BookmarkNext<cr>zt`/`:BookmarkPrev<cr>zt` works as well
