### ISSUE TITLE
BookmarkNext across buffers

### ISSUE THREAD

**Issue by fbcotter** [MattesGroeger/vim-bookmarks#151]
Is it possible to cycle through bookmarks in different buffers? At the moment, I can bring up the list of bookmarks and choose which one I go to, but I think it would be nice sometimes to cycle through forwards and backwards through this list.

**Comment by MattesGroeger** [comment]
As this seem to be not such a highly requested feature I suggest solving this with your own little function in the `.vimrc`. But thanks for your suggestion 🙏

**Comment by MattesGroeger** [comment]
If you manage to write something up, please share it here and I can put it in the `FAQ` section.

**Comment by kdnk** [comment]
@fbcotter I made a plugin for it. https://github.com/kdnk/bookmarks-cycle-through.nvim
