### ISSUE TITLE
No bookmarks when toggling bookmarks through vim command

### ISSUE THREAD

**Issue by abdelmaged** [MattesGroeger/vim-bookmarks#152]
When opening vim with command arguments that toggle bookmarks on certain lines, it shows message "Bookmark Added", however no bookmark are actually in the bookmark list. 

Example:
vim testfile -c ":2" -c ":BookmarkToggle"

**Comment by MattesGroeger** [comment]
Sounds like a similar issue as #133 ... I wonder if this is due to some lazy initialisation, e.g. due to filesystem access? I'm closing this for now as it does not seem to be a high-request issue.
