### ISSUE TITLE
Cannot jump from quickfix (show all) list with enter key

### ISSUE THREAD

**Issue by rcrx** [MattesGroeger/vim-bookmarks#156]
# Problem:

It works in conjunction with `<s-v>`, meaning a jump will not be performed without first selecting the entire line. `<cr>` alone does nothing. I have tried removing & re-installing the plugin while eliminating all lines in vimrc pertaining to vim-bookmarks with no success.

Quickfix list functions properly when using ctrl-p. The ctrl-p window, however, provides no file information, only the verbatim annotation or line content without any indication of file association.

![Screenshot from 2020-04-21 09-03-11](https://user-images.githubusercontent.com/29853107/79881931-1733af00-83af-11ea-80ce-2cb6cd1d6fde.png)

`BookmarkNext` and `BookmarkPrev` operate normally.

# Resolution:
Adding the line `nmap <cr> <s-v><cr>` to `bm#location_list()` in `vim-bookmarks/autoload/bm.vim` seems to rectify the annoyance.

**Comment by MattesGroeger** [comment]
Hi @rcrx ,

first of all thx a lot for your elaborate issue description including a screenshot. I have to admit I can't fully follow you as to what the exact problem is. 

What is this `<s-v>` shortcut?
Where do you want to jump to?
Is your resolution something to put in the plugin or that is just for your personal use?

I hope you can help us better understand how to proceed from here. Please re-open the issue if still relevant.
