### ISSUE TITLE
search annotation with ctrlp: Error detected while processing function <SNR>52_AcceptSelection[27]..ctrlp#bookmarks#accept

### ISSUE THREAD

**Issue by Tokubara** [MattesGroeger/vim-bookmarks#162]
I use this plugin with ctrlp.
I create a bookmark with annotation by mi.
I press ma, open all bookmarks and search annotation(in ctrlp window).
I find it and press <cr>, then I get the error message:
```
Error detected while processing function <SNR>52_AcceptSelection[27]..ctrlp#bookmarks#accept:
line   18:
E37: No write since last change (add ! to override)
```

If I write the file after I create a bookmark, no error happens.

##### vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2021 22:31:39)
macOS version - x86_64
Included patches: 1-2526
Compiled by Homebrew
```

##### plugin version
the latest by far

**Comment by MattesGroeger** [comment]
I was unable to reproduce this issue (same env). Maybe I'm missing something? Is there an unsaved file involved?
