### ISSUE TITLE
.vim-bookmarks file always saved to edited file's directory instead of set location

### ISSUE THREAD

**Issue by eggbean** [MattesGroeger/vim-bookmarks#179]
This is the relevant parts of my config:

```
if has('unix')
  let $VIM = "$HOME/.config/vim"
elseif has('win32')
  let $VIM = "$HOME/vimfiles"
endif

" vim-bookmarks
  let g:bookmark_sign = '⭕'
  let g:bookmark_save_per_working_dir = 0
  let g:bookmark_manage_per_buffer = 1
  let g:bookmark_auto_save_file = $VIM .'/vim-bookmarks'
  let g:bookmark_display_annotation = 1
```

No matter how I set `g:bookmark_auto_save_file` the `.vim-bookmarks` file always get saved in the same directory as the file with the bookmarks set. What am I doing wrong?

**Comment by Swivelgames** [comment]
Is your `$VIM` writable?

What do you get when you type `:!ls -ld $VIM`?

```
drwxr-xr-x 4 root root 4096 Jul  3  2022 /usr/share/vim
```

**Comment by eggbean** [comment]
Vim:
    :!ls -ld $VIM
    drwxr-xr-x 5 root root 4096 Nov 20 16:12 /usr/share/vim

Neovim:

    :!ls -ld $VIM                                                                             
    drwxr-xr-x 3 root root 0 Apr  7 12:40 /tmp/.mount_nvimo6AEur/usr/share/nvim

**Comment by eggbean** [comment]
I seem to have stopped trying to redefine `$VIM`. IIRC, it caused problems.

Vim:

    :!ls -ld $VIM
    drwxr-xr-x 5 root root 4096 Nov 20 16:12 /usr/share/vim

Neovim:

    :!ls -ld $VIM
    drwxr-xr-x 3 root root 0 Apr  7 12:40 /tmp/.mount_nvimo6AEur/usr/share/nvim

I use on Neovim appimage on x86_64 hosts and Vim everywhere else. When I go to `$VIM` in the neovim terminal it says it's a read only system and I cannot make any files in the vim `$VIM` location either.

So, that's the problem. Cheers.

**Comment by eggbean** [comment]
I went to change my config and saw that I have already changed it, but `!ls -ld "$XDG_DATA_HOME/vim/bookmarks"` says that the location doesn't exit. I changed it to `"$XDG_DATA_HOME/vim"` and it seems to be okay now. Thanks.
```
" vim-bookmarks
let g:bookmark_sign = '⭕'
let g:bookmark_save_per_working_dir = 0
let g:bookmark_manage_per_buffer = 0
let g:bookmark_auto_save_file = '$XDG_DATA_HOME/vim/bookmarks'
let g:bookmark_display_annotation = 1
```
`bookmark_manage_per_buffer` also needs to be `0`.

**Comment by Swivelgames** [comment]
Glad you got it figured out! I was afraid that was the case haha. I set mine to `$XDG_DATA_HOME` as well. 
In order to fix that, I believe I used:

```
mkdir -p $XDG_DATA_HOME/vim
touch $XDG_DATA_HOME/vim/bookmarks
```
