### ISSUE TITLE
Automatically close :BookmarkShowAll window after selection

### ISSUE THREAD

**Issue by cosineblast** [MattesGroeger/vim-bookmarks#184]
Hi there, I've been using this plugins for a few weeks, and it has been working really well, but there is this little detail that has been annoying me: After running :BookmarkShowAll and selecting an option, it does not close the BookmarkShowAll window, so I have to setup a keybinding to close it, or close it manually. Is there any known solution to make so that it closes the window after I select a bookmark/annotation?

**Comment by crumbtoo** [comment]
Hey! Add this to your config:
```viml
let g:bookmark_auto_close = 1
```

**Comment by cosineblast** [comment]
OH. Sorry. I have glossed over seen that option. Thanks!
