### ISSUE TITLE
Conflict with NERDTree

### ISSUE THREAD

**Issue by jherdman** [MattesGroeger/vim-bookmarks#38]
When viewing a directory tree with NERDTree, the `ma` command is supposed to add a new child node in a directory, which vim-bookmarks seems to hijack. This makes me sad :(

**Comment by Nitive** [comment]
I just rebind all key maps when switch between NERDTree and files

	let g:bookmark_no_default_key_mappings = 1
	function! BookmarkMapKeys()
		nmap mm :BookmarkToggle<CR>
		nmap mi BookmarkAnnotate<CR>
		nmap ma BookmarkShowAll<CR>
		nmap mj BookmarkNext<CR>
		nmap mk BookmarkPrev<CR>
		nmap mc BookmarkClear<CR>
		nmap mx BookmarkClearAll<CR>
	endfunction
	function! BookmarkUnmapKeys()
		unmap mm
		unmap mi
		unmap ma
		unmap mj
		unmap mk
		unmap mc
		unmap mx
	endfunction
	autocmd BufEnter * :call BookmarkMapKeys()
	autocmd BufEnter NERD_tree_* :call BookmarkUnmapKeys()

**Comment by MattesGroeger** [comment]
@Nitive That's great, thanks! I'll put it in the readme :+1:

**Comment by winzenith** [comment]
I've figured another way to solve the issue. Just in case if anyone wants to avoid remapping and have an alternative way to workaround. Once switched in Nerdtree, press **m** and **<leader>** ( my leader key has set to comma ) , I think that way the leader key would seems to break the action of listening to triggering keys, and it will instantly show up the menu. So you don't need to remap those default keys.
