### ISSUE TITLE
Not showing loaded bookmarks

### ISSUE THREAD

**Issue by rfree2** [MattesGroeger/vim-bookmarks#48]
When I place bookmarks (mm) and quit vim and reopen same file again,
then old bookmaks work I can jump o them using mn and mp, but:

1) the line for symbols is not shown (until I place additional bookmarks in this vim run using mm again)
2) even after adding new bookmarks, only the new bookmarks are visible with a symbols, the old ones remain hidden. When using highlight, only new lines are highlighted too;

My setup: I load with pathogen#infect , installed to:
ls ~/.vim/bundle/vim-bookmarks-1.1.0/
autoload  doc  LICENSE  plugin  vim-bookmarks-1.1.0.zip

my ~/.vimrc
source ~/.vim/vimrc

and my  ~/.vim/vimrc

syntax on

set nocompatible

set shiftwidth=2
set tabstop=2
set autoindent

source ~/.vim/bin/minibufexpl.vim
source ~/.vim/bundle/lastpos.vim 

 " source ~/.vim/bundle/vim-bookmarks/autoload/bm_sign.vim 
 " source ~/.vim/bundle/vim-bookmarks/plugin/bookmark.vim

imap <C-PageDown> <ESC><C-PageDown>
map <C-PageDown> :bnext!<CR>
imap <C-PageUp> <ESC><C-PageUp>
map <C-PageUp> :bprev!<CR>

imap <F8> <ESC><F8>
map <F8> :w<CR>:make run<CR>
imap <F9> <ESC><F9>
map <F9> :w<CR>:make run<CR>
map <S-F9> :cn<CR>
map <C-F9> :cp<CR>

imap ` <C-N>

set hlsearch
nnoremap <C-M> :let @/='<<C-R>=expand("<cword>")<CR>>'<CR>:set hls<CR>
nnoremap <C-N> :noh<CR>

set nu

call pathogen#infect() 

" www.vim.org/scripts/script.php?script_id=4893
let g:bookmark_auto_save = 1
let g:bookmark_highlight_lines = 1
" ctrl-B is toggling bookmarks
imap <C-B> <Esc><C-B>i
" map <C-B> :ToggleBookmark<CR>
" use mm in normal mode

**Comment by Matt-Deacalion** [comment]
I have the same problem - it disappears when I disable the `vim-signify` plugin.
