### ISSUE TITLE
Setting to Disable Default Mappings

### ISSUE THREAD

**Issue by angelic-sedition** [MattesGroeger/vim-bookmarks#68]
If there are mappings that someone doesn't want to use (for example, I don't want mx), dummy mappings have to be used to override them. I think it would be nice to also have a setting to disable default mappings instead of having to do this.

**Comment by MattesGroeger** [comment]
Great idea, I'd be happy to accept your pull request :+1:

**Comment by MattesGroeger** [comment]
Closed by #69

**Comment by angelic-sedition** [comment]
Thanks for merging!
