### ISSUE TITLE
[Request] Do not close Unite interface when 'delete' action has executed.

### ISSUE THREAD

**Issue by lambdalisue** [MattesGroeger/vim-bookmarks#70]
The current behavior is not following general unite behavior.

I'll send a pull request while I add the new Unite interface but I don't have enough time to fix it right now so this issue is a remidner to @lambdalisue

Or do you like current behavior (Unite interface will be closed when user execute 'delete' action) ?

**Comment by MattesGroeger** [comment]
As I personally don't use Unite, I don't mind the current behavior ;)

Thanks for your effort! I'll keep the issue here.
