### ISSUE TITLE
BookmarkShowAll removes all bookmarks

### ISSUE THREAD

**Issue by jgonera** [MattesGroeger/vim-bookmarks#74]
Is that supposed to happen? Am I misunderstanding how it's supposed to work? Latest master of the plugin, Vim 7.4.488.

**Comment by yinlubin** [comment]
I also met this issue, very annoying.

**Comment by MattesGroeger** [comment]
Hi, thanks for reporting this issue. Unfortunately I'm not able to reproduce this. Could you please describe the exact steps on how to reproduce it? Thanks in advance!

**Comment by fuzhuo** [comment]
I also meet this issue, Tested at mac 10.10.3 and ubuntu12.04.2
VIM version - Vi IMproved 7.3

All bookmarks will be deleted when switch to another split window not only swith to window show all bookmarks.

1. vim a.txt
2. mm
3. :sp b (or press ma)
The bookmark of a.txt was deleted...

**Comment by nagolove** [comment]
Hello! I have the same problem..

Vim version 7.4, win32 build on win7 64 bit

```
~/.vimrc
...
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'MattesGroeger/vim-bookmarks'
call vundle#end()            " required
...
```

1. open file
2. Some mm commans
3. ma
4. ma

All bookmarks list was cleared.

**Comment by jessecfisher** [comment]
I also experience this issue.

I do not experience this issue when using this commit: 2e11d20b687055a8a673a9361beb4e8243c4d573

**Comment by MattesGroeger** [comment]
@jessecfisher thanks so much for looking into this and providing a solution. I'll try to review this asap and create a new version. Really sorry for all the inconvenience! Much appreciated :+1:

**Comment by xanderdunn** [comment]
This always happens to me as well.

**Comment by jmcantrell** [comment]
`let g:bookmark_manage_per_buffer = 1` worked for me. It looks like the call to s:refresh_line_numbers here https://github.com/MattesGroeger/vim-bookmarks/blob/master/plugin/bookmark.vim#L182 is resetting the boomarks to what they were on the last save?

**Comment by rgrinberg** [comment]
Can confirm that this bug happens to me as well. Makes the plugin unusable.

**Comment by cl20vv** [comment]
this bug happens to me too, and let g:bookmark_manage_per_buffer = 1 in .vimrc works well, thanks @jessecfisher

**Comment by polm** [comment]
I also ran into this and managed to work around it with `let g:bookmark_manage_per_buffer = 1`.

**Comment by cj** [comment]
I had the same issue.  `let g:bookmark_manage_per_buffer = 1` fixed it.

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:34)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
  +acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
        user vimrc file: "$HOME/.vimrc"
         2nd user vimrc file: "~/.vim/vimrc"
               user exrc file: "$HOME/.exrc"
                 fall-back for $VIM: "/usr/share/vim"
                 Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1
                 Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
```

**Comment by a-d-v-e-n-t-u-r-o-u-s** [comment]
The same issue by me, `let g:bookmark_manage_per_buffer = 1` saves the day for a while.

**Comment by ashwinravianandan** [comment]
I face the same issue.   The issue seems to be with the auto command to save the bookmarks file. It only saves the bookmarks on leaving vim.  Leaving buffers triggers the s:set_up_auto_save, which ends up clearing all bookmarks and loading the old ones from the file.
@MattesGroeger : I have submitted a pull request that fixes this issue.  Could you please review it?  It fixes the issue for me.

**Comment by MattesGroeger** [comment]
@ashwinravianandan great, thanks a lot. Can other people confirm that it works now with the latest version?

**Comment by a-d-v-e-n-t-u-r-o-u-s** [comment]
After pulling current master with SHA-1 
`c1cfec17fd81f51411e559ea32c97ce8f5510b0c`
and setting bookmarks per working dir as you sugessted in README file with: 

`let g:bookmark_save_per_working_dir = 1
let g:bookmark_auto_save = 1`

bookmarks are saved but file `.vim-bookmarks` isn't saved in directory from which I've opened vim, but it is saved into my `$HOME` directory ? 

@ashwinravianandan was it your pull request ? or do I have something messed up with my vim ?

Can others confirm similar behaviour ?

**Comment by ashwinravianandan** [comment]
@a-d-v-e-n-t-u-r-o-u-s : I don't think it is related to my pull request.  I have just added an additional trigger point for auto saving.  For the purpose of debugging could you try defining the below function in your vimrc?  I couldn't find a default implementation for this.

" Finds the Git super-project directory.
function! g:BMWorkDirFileLocation()
    let filename = 'bookmarks'
    let location = ''
    if isdirectory('.git')
        " Current work dir is git's work tree
        let location = getcwd().'/.git'
    else
        " Look upwards (at parents) for a directory named '.git'
        let location = finddir('.git', '.;')
    endif
    if len(location) > 0
        return location.'/'.filename
    else
        return getcwd().'/.'.filename
    endif
endfunction

**Comment by cl20vv** [comment]
@MattesGroeger I've tried, It works.
thanks to @ashwinravianandan , good job.

**Comment by cl20vv** [comment]
@a-d-v-e-n-t-u-r-o-u-s 
```
let g:bookmark_save_per_working_dir = 1
let g:bookmark_auto_save = 1
```
works for me.

**Comment by MattesGroeger** [comment]
@a-d-v-e-n-t-u-r-o-u-s @cl20vv Thanks for testing
@ashwinravianandan Thanks again for fixing the issue :+1: 
@a-d-v-e-n-t-u-r-o-u-s please open a new ticket if needed
