### ISSUE TITLE
Bookmark saving doesn't work when quitting vim using :q if bookmark_manage_per_buffer is active

### ISSUE THREAD

**Issue by mildred** [MattesGroeger/vim-bookmarks#75]
Opening a file, setting some bookmarks and closing using `:q` doesn't save the bookmarks. The file `~/.vim-bookmarks` does not contains the bookmarks.

If I however delete the buffer using `:bd`, then the bookmarks are saved.

**Comment by mildred** [comment]
I think I understand what happens: `g:bookmark_manage_per_buffer` is set to 1 on my configuration, and when looking at the active `autocmd` I have:

    :autocmd bm_auto_save 
    --- Auto-Commands ---
    bm_auto_save  BufLeave
        *         call s:auto_save()
    bm_auto_save  BufWinEnter
        *         call s:add_missing_signs(expand('<afile>:p'))

There is no autocmd for `VimLeave`. This is because of the following code in [plugin/bookmark.vim#L50](/MattesGroeger/vim-bookmarks/blob/master/plugin/bookmark.vim#L50):

     if g:bookmark_manage_per_buffer ==# 1
       augroup bm_auto_save
         autocmd BufLeave * call s:auto_save()
       augroup END
     else
       augroup bm_auto_save
         autocmd VimLeave * call s:auto_save()
       augroup END
     endif

Why not change that code to:

     if g:bookmark_manage_per_buffer ==# 1
       augroup bm_auto_save
         autocmd BufLeave * call s:auto_save()
       augroup END
     endif
     augroup bm_auto_save
       autocmd VimLeave * call s:auto_save()
     augroup END

**Comment by MattesGroeger** [comment]
This should be fixed by now. Sorry for the late reply.
