### ISSUE TITLE
E239? 

### ISSUE THREAD

**Issue by IanQS** [MattesGroeger/vim-bookmarks#76]
Starting up a file without any book marks and adding one:
E239: Invalid sign text: X�

Opening a file with bookmarks inside it already: 
Error detected while processing function <SNR>49_init..<SNR>49_set_up_auto_save..<SNR>49_startup_load_bookmarks..<SNR>49_add_missing_signs..bm_sign#add_at..bm_sign#lazy_init..bm_sign#init:
line    5:
E239: Invalid sign text: X�

I'm running arch linux if that helps. I can paste my vimrc if you'd like.

**Comment by MattesGroeger** [comment]
Duplicate #78
