### ISSUE TITLE
E239: Invalid sign text: X� when using mm

### ISSUE THREAD

**Issue by IanQS** [MattesGroeger/vim-bookmarks#78]
I tried googling and all I found were errors related to some other issue.

**Comment by MattesGroeger** [comment]
Sorry for the late reply. It sound's to me like an encoding issue. Could you please try to set the signs to characters that don't require UTF-8?

```
let g:bookmark_sign = '>>'
let g:bookmark_annotation_sign = '##'
```

... and see if the problem persists?
