### ISSUE TITLE
switching buffers clears bookmarks

### ISSUE THREAD

**Issue by ashwinravianandan** [MattesGroeger/vim-bookmarks#86]
In the latest version of vim-bookmarks (commit hash 56b5baae819812e9584fb3df182323a66117da09 ), and in some older versions, using "na" opens the bookmarks list in the quick fix windows.  But all existing bookmarks are cleared.

I am using a fresh install of the plugin with zero configuration.  

Modifying the init function as below fixed the issue but this doesn't seem to be the root cause.
<pre>
function! s:init(file)
  if g:bookmark_auto_save ==# 1 &&  g:bookmark_manage_per_buffer ==# 1
</pre>
g:bookmark_manager_per_buffer is 0 by default and hence with the auto commands disabled things work fine. The issue is observed on creating the augroup  _bm_vim_enter_ .

**Comment by ashwinravianandan** [comment]
Issue seems to be in the BookmarkLoad function.  I do not get a confirm prompt asking if the bookmarks can be cleared, but the local confirm variable is initialized to 1.  So the auto command triggering auto save ends up clearing my bookmarks without prompting anything.

**Comment by ashwinravianandan** [comment]
Submitted pull request.

**Comment by ashwinravianandan** [comment]
Root cause identified.  if g:bookmark_manage_per_buffer is not set, the autocommand to save bookmarks is created for the VimLeave event.  

A BufEnter is triggered every time we switch buffers and the handler ends up clearing all bookmarks and only using the ones in the file.  A pull request has been submitted with a fix.  Kindly review it.

**Comment by MattesGroeger** [comment]
Fixed with pr #89 ... thanks!
