### ISSUE TITLE
Bookmarks disappear after a while.

### ISSUE THREAD

**Issue by trusktr** [MattesGroeger/vim-bookmarks#88]
I'm not sure why.

One way to clear bookmarks manually is to type `:e<cr>`. But I'm not doing that, so I'm not sure what eventually causes bookmarks to be cleared.

**Comment by ashwinravianandan** [comment]
Hi trusktr,

Are bookmarks getting cleared on switching buffers?  I'm observing the same issue.  Setting g:bookmark_manage_per_buffer to 1 should mask the issue for the time being.

**Comment by MattesGroeger** [comment]
@trusktr Yes, please try if you still experience the issue with the latest version that includes the fix provided by @ashwinravianandan

**Comment by trusktr** [comment]
Indeed, that fixes the problem, although the gutter still disappears when switching between buffers, but it comes back when I return to the buffer with the bookmarks in tact.
