### ISSUE TITLE
Unknown function: unite#custom#profile

### ISSUE THREAD

**Issue by tenfyzhong** [MattesGroeger/vim-bookmarks#90]
when i add 
call unite#custom#profile('source/vim_bookmarks', 'context', {
    \   'winheight': 13,
    \   'direction': 'botright',
    \   'start_insert': 0,
    \   'keep_focus': 1,
    \   'no_quit': 1,
    \ })

to my .vimrc

it remind me "Unknown function: unite#custom#profile"

**Comment by MattesGroeger** [comment]
As discussed in #121 we should drop the unite-support all together as the project is not maintained anymore and creates complexity and regressions within `vim-bookmarks`.
