### ISSUE TITLE
Generate annotated source code in markdown

### ISSUE THREAD

**Issue by m42e** [MattesGroeger/vim-bookmarks#94]
Hi,

I just had the idea, that it would be somehow a nice feature to generate a annotated sourcecode in markdown using the bookmarks set.

What do you think?

Thanks a lot.

**Comment by MattesGroeger** [comment]
Hey @m42e ,

sorry for the late reply 🙄  ... if you are still active and interested in this idea please re-open this issue and further elaborate. As there are no 👍  I'm assuming it's not a high-demand feature.

Closing for now.
