### ISSUE TITLE
Can only jump one bookmark at a time

### ISSUE THREAD

**Issue by liitii** [MattesGroeger/vim-bookmarks#95]
if I want to jump 3 bookmarks, I have to type `mnmnmn`. `3mn` gives me _E481: No range allowed_.

**Comment by liitii** [comment]
Same problem for `mkk` and `mjj`.

**Comment by nkgm** [comment]
Guess this can be closed now

**Comment by MattesGroeger** [comment]
Yes 👍 fixed with #119
